services:
  kyosei-dash:
    build:
      context: .
      dockerfile: docker/dockerfile
    container_name: kyosei-dash
    restart: unless-stopped
    volumes:
      - ./data:/app/data
    ports:
      # <Host Port>:<Container Port>
      - "3001:3001"
